version: "3"
services:
  python_container_0:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=0
      - PORT_NUMBER=40000
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  python_container_1:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=1
      - PORT_NUMBER=40001
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_2:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=2
      - PORT_NUMBER=40002
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_3:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=3
      - PORT_NUMBER=40003
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_4:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=4
      - PORT_NUMBER=40004
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

# -------- 10 NODES -------- #

  python_container_5:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=5
      - PORT_NUMBER=40005
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_6:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=6
      - PORT_NUMBER=40006
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_7:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=7
      - PORT_NUMBER=40007
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_8:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=8
      - PORT_NUMBER=40008
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_9:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=9
      - PORT_NUMBER=40009
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0
