version: "3"
services:
  python_container_0:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=0
      - PORT_NUMBER=40000
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  python_container_1:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=1
      - PORT_NUMBER=40001
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_2:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=2
      - PORT_NUMBER=40002
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_3:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=3
      - PORT_NUMBER=40003
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0

  python_container_4:
    build: .
    network_mode: "host"
    environment:
      - CONTAINER_NUMBER=4
      - PORT_NUMBER=40004
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - python_container_0
