version: "3"
services:
  python_container_0:
    build: .
    environment:
      - CONTAINER_NUMBER=0
      - PORT_NUMBER=40000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "40000:40000"

  python_container_1:
    build: .
    environment:
      - CONTAINER_NUMBER=1
      - PORT_NUMBER=40001
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "40001:40001"
    depends_on:
      - python_container_0

  python_container_2:
    build: .
    environment:
      - CONTAINER_NUMBER=2
      - PORT_NUMBER=40002
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "40002:40002"
    depends_on:
      - python_container_0

    
  python_container_3:
    build: .
    environment:
      - CONTAINER_NUMBER=3
      - PORT_NUMBER=40003
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "40003:40003"
    depends_on:
      - python_container_0

  python_container_4:
    build: .
    environment:
      - CONTAINER_NUMBER=4
      - PORT_NUMBER=40004
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "40004:40004"
    depends_on:
      - python_container_0
